version: '3'

services:
  python:
    container_name: python
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - 5000:5000
    build:
        context: ./python
        dockerfile: Dockerfile
    depends_on:
        - db
    volumes:
        - ./python/scripts:/usr/src/app/
    networks:
      - mynetwork
  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - dblog:/var/log/mysql
    networks:
      - mynetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
    networks:
      - mynetwork
volumes:
  dbdata: {}
  dblog: {}
networks:
  mynetwork:
    driver: bridge